import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import mentor from "../public/assets/mentor.jpg";
import student from "../public/assets/student.jpg";
import senior from "../public/assets/senior.jpg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Accueil</h1>
      <Image src={mentor} layout="responsive" placeholder="blur" />
    </div>
  );
}
